Apply minor styling updates
k-o-t-n/piston pull request #6
Opened 2016-09-19 19:46 UTC by mattdsmith89

2016-09-19 19:47 UTC, mattdsmith89 commented
Much white space updates, stupid auto-format 😞

2016-09-19 21:24 UTC, daveraine commented on src/Piston/Views/Post/_Preview.cshtml
> +        @model Piston.Models.Post
Why this not first line? :confused:

2016-09-19 21:25 UTC, daveraine commented on src/Piston/scss/base.scss
> +$banner-font-color: white;
Overrides go in scss/styles/_variables-colors.scss yo :sunglasses:

2016-09-19 21:26 UTC, daveraine requested changes

2016-09-19 22:25 UTC, mattdsmith89 commented on src/Piston/Views/Post/_Preview.cshtml
> +        @model Piston.Models.Post
Because I wasn't paying attention 😄

2016-09-19 22:25 UTC, mattdsmith89 commented on src/Piston/scss/base.scss
> +$banner-font-color: white;
I did look to see if you had overrides somewhere, that wasn't at all obvious! 😛

2016-09-20 08:23 UTC, daveraine commented on src/Piston/scss/base.scss
> +$banner-font-color: white;
It was the default folder structure from the base download so I left it. I think we should move all the ad-hoc styling from site.scss into individual files to make it easier to manage, will make an issue for that.

2016-09-20 08:53 UTC, daveraine commented
Here's what it looks like now:

![home](https://cloud.githubusercontent.com/assets/4315787/18663830/0dae5394-7f18-11e6-9b26-35151f117427.png)

![post](https://cloud.githubusercontent.com/assets/4315787/18663831/0db0ad9c-7f18-11e6-9d38-ce8698c25d75.png)

2016-09-20 12:43 UTC, mattdsmith89 commented
It's not perfect by all means, I was really just making it look less like the base.. base style. 

There are still plenty of issues with it:
 - the HRs look weird on the main page
 - review text might be a bit too wide
 - score looks a bit off
 - when the scroll bar appears, everything shifts left a bit which looks naff
 - review byline doesn't match front page (should it?)

I'm sure there are many more.

Should probably open an issue (or many issues) about styling the site properly really.

2016-09-20 12:57 UTC, Kitcheone commented
:+1:

2016-09-20 13:14 UTC, daveraine commented
Ok. I suggest you make issues for those points (or combine into one issue, whatevs) and we will merge this. I think it's a good start, maybe needs more colour. Might need links in the header at some point. You got any comments @Kitcheone?

2016-09-20 13:14 UTC, daveraine approved these changes

2016-09-20 13:31 UTC, mattdsmith89 commented
Yeah I agree with that. It's definitely lacking colour, but I think reviews should probably have images too and that would help. Also agree with links in the header - just need to be careful when viewing the site on a small device. Don't think this "framework" will auto-collapse the header menu like bootstrap does. Would get hideously messy on mobile if we don't implement something like that.

2016-09-20 13:33 UTC, Kitcheone commented
Yeah I think it needs colour and a lot more work, but it's already better than base base.

Put those issues somewhere - github project for front end?

2016-09-20 13:51 UTC, mattdsmith89 commented
Opened issue #8 to cover this for now.

2016-09-20 16:18 UTC, merged